# Generated by Django 6.0.7 on 2026-07-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo_original', models.FileField(upload_to='planilhas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('total_produtos', models.IntegerField(default=0)),
                ('produtos_baixa_conversao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoAnalisado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avaliacao_media', models.FloatField()),
                ('num_avaliacoes', models.IntegerField()),
                ('investimento_ads', models.DecimalField(decimal_places=2, max_digits=10)),
                ('probabilidade_conversao', models.FloatField()),
                ('previsao_classe', models.CharField(max_length=50)),
                ('diagnostico_causa', models.TextField(blank=True, null=True)),
                ('plano_acao_cro', models.TextField(blank=True, null=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core_app.relatoriobatch')),
            ],
        ),
    ]
